project:
  type: website
  
cache: true

website:
  title: "Aulas"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: Aula1.qmd
        text: Introdução
        icon: book
      - href: Aula2.qmd
        text: Gráficos
        icon: bar-chart-line
      - href: Aula3.qmd
        text: Teste T
        icon: clipboard-data
      - href: Aula4.qmd
        text: ANOVA
        icon: diagram-3
      - href: Aula5.qmd
        text: Testes de médias
        icon: ui-checks
        
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual